version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: velopick
      MONGO_INITDB_ROOT_USERNAME: veloss
      MONGO_INITDB_ROOT_PASSWORD: velopick
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
